package dadosrda;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label(value = "dados do RDA")
public class dadosrda implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    @org.kie.api.definition.type.Label(value = "teste")
    @org.kie.api.definition.type.Position(value = 0)
    private java.lang.String teste;

    public dadosrda() {
    }
    
    public dadosrda(java.lang.String teste) {
        this.teste = teste;
    }

    public java.lang.String getTeste() {
        return this.teste;
    }
    
    public void setTeste(java.lang.String teste) {
        this.teste = teste;
    }

}